name: Build AOSP ROM

on:
  workflow_dispatch:
  push:
    branches:
      - termux-build

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ROM for Redmi 12 5G

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Environment
        run: |
          echo "🔧 Basic build environment setup test..."

      - name: Dummy AOSP Sync
        run: |
          echo "📦 Skipping actual repo sync for test build."

      - name: Dummy Build Step
        run: |
          echo "✅ Workflow test build successful."

