name: Build AOSP ROM


on:
  workflow_dispatch:
  push:
    branches:
      - termux-build

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ROM for Redmi 12 5G

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential curl \
          flex g++-multilib gcc-multilib git gnupg gperf imagemagick \
          lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool \
          libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils \
          lzop pngcrush rsync schedtool squashfs-tools xsltproc zip \
          zlib1g-dev ccache openjdk-11-jdk repo

      - name: Initialize repo
        run: |
          mkdir rom && cd rom
          repo init -u https://github.com/PixelExperience/manifest -b thirteen
          repo sync -c --no-tags --no-clone-bundle -j8

      - name: Setup ccache
        run: |
          export USE_CCACHE=1
          ccache -M 50G

      - name: Dummy Build Step
        run: |
          echo "🎯 Ready to build — ab device source aur tweaks add honge"
